// {{projectName}} — generated by EdgeForge
export default {
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);
    const body = { ok: true, project: "{{projectName}}", path: url.pathname };
    return new Response(JSON.stringify(body, null, 2), {
      headers: { "content-type": "application/json" },
    });
  },
};